// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from winlose.djinni

#ifndef DJINNI_GENERATED_NJSWINLOSE_HPP
#define DJINNI_GENERATED_NJSWINLOSE_HPP


#include <memory>
#include <string>

#include <nan.h>
#include <node.h>
#include "../src/api/Winlose.hpp"

using namespace v8;
using namespace node;
using namespace std;
using namespace api;

class NJSWinlose: public Nan::ObjectWrap {
public:

    static void Initialize(Local<Object> target);
    virtual ~NJSWinlose() {};
    NJSWinlose(const std::shared_ptr<api::Winlose> &iWinlose):_Winlose(iWinlose){};

    static Handle<Object> wrap(const std::shared_ptr<api::Winlose> &object);
    static Nan::Persistent<ObjectTemplate> Winlose_prototype;
    std::shared_ptr<api::Winlose> getCppImpl(){return _Winlose;};

private:
    static NAN_METHOD(getVersion);

    static NAN_METHOD(New);

    static NAN_METHOD(isNull);
    std::shared_ptr<api::Winlose> _Winlose;
};
#endif //DJINNI_GENERATED_NJSWINLOSE_HPP
