// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

declare class NJSWinloseNodeJS
{
    declare function add(lhs1: number, lhs2: number): number;
}
declare class NJSWinlose
{
    static declare function getVersion(): string;
    declare function callAdd(lhs1: number, lhs2: number): number;
    static declare function newInstance(operation: NJSWinloseNodeJS): NJSWinlose;
}
