// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from winlose.djinni

#ifndef DJINNI_GENERATED_WINLOSE_HPP
#define DJINNI_GENERATED_WINLOSE_HPP

#include <string>

namespace api {

class Winlose {
public:
    virtual ~Winlose() {}

    static std::string getVersion();
};

}  // namespace api
#endif //DJINNI_GENERATED_WINLOSE_HPP
