// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from winlose.djinni

#ifndef DJINNI_GENERATED_WINLOSENODEJS_HPP
#define DJINNI_GENERATED_WINLOSENODEJS_HPP

#include <cstdint>

namespace api {

class WinloseNodeJS {
public:
    virtual ~WinloseNodeJS() {}

    virtual int32_t add(int32_t lhs1, int32_t lhs2) = 0;
};

}  // namespace api
#endif //DJINNI_GENERATED_WINLOSENODEJS_HPP
